### ISSUE TITLE
Wheel odom covariance limited to 2Hz rate ?

### ISSUE THREAD

**Issue by nvandamme** [LeoRover/leo_robot#8]
https://github.com/LeoRover/leo_robot/blob/b3a220518552abb75d2afc4a98f3ea27de3b06b7/leo_fw/src/firmware_message_converter.cpp#L126

**Comment by bjsowa** [comment]
> https://github.com/LeoRover/leo_robot/blob/b3a220518552abb75d2afc4a98f3ea27de3b06b7/leo_fw/src/firmware_message_converter.cpp#L126

This line has nothing to do with the frequency of publishing messages.

The firmware_message_converter node will publish wheel odom as fast as it can, limited to the rate at which the firmware is publishing the odometry, which is 20 Hz IIRC.
